# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [ push, pull_request ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Install dependencies
      run: sudo apt install cmake g++ libjpeg-dev libpng-dev libprotobuf-dev libwebp-dev libgtest-dev ninja-build protobuf-compiler valgrind

    # Build the code
    - name: Build
      run: |
        mkdir build && cd build && cmake -G "Ninja" ../ && ninja 
    
    # Run tests
    - name: Run tests
      run: valgrind ./build/test/test_thumbnailer
